version: '3'

services:
  dashboard:
    image: manifoldco/demo-app
    ports:
      - 3001:3001
    environment:
      - PORT=${PORT:-3001}
      - REACT_APP_STRIPE_KEY=pk-docker-compose-supersecret
      - REACT_APP_SEGMENT_KEY=segment-docker-compose-secret
